### ISSUE TITLE
Link to web-site is 404

### ISSUE THREAD

**Issue by novakov-alexey** [ChristopherDavenport/circuit-http4s#60]
It seems link to documentation is broken: https://christopherdavenport.github.io/circuit-http4s

**Comment by ChristopherDavenport** [comment]
Whoops I always forget to push that gh-pages branch. My apologies. Interrim javadocs 

Client - https://www.javadoc.io/doc/io.chrisdavenport/circuit-http4s-client_2.12/0.2.0
Server - https://www.javadoc.io/doc/io.chrisdavenport/circuit-http4s-server_2.12/0.2.0

**Comment by novakov-alexey** [comment]
Thanks, looking forward for that branch :-)

**Comment by ChristopherDavenport** [comment]
Site now exists. But it doesn't presently have much more than the readme does.

Would love if you wanted to add stuff to it, but no worries I can get to it eventually.
